Remove sed processing, add -nocppc option
* The sed processing is no longer needed because we can handle its effects entirely with the Architecture file code and the Faust compiler options.
* Add a -nocppc option to generate the CPP code with Faust but NOT compile it.

diff --git a/srcs/install/install-sdk b/srcs/install/install-sdk
--- a/srcs/install/install-sdk
+++ b/srcs/install/install-sdk
@@ -13,8 +13,11 @@ cd $(realpath $(dirname $0))
 ##
 ## Is the Stratus connected
 ##
-TARGET_ADDRESS=stratus.local # the first script argument
-ping -c 1 -q $TARGET_ADDRESS >/dev/null 2>&1 || { echo "Cannot find Stratus connection. Please connect Stratus to your computer via USB"; false; }
+TARGET_ADDRESS=${1:-root@stratus.local} # the first script argument
+TARGET_USER=${TARGET_ADDRESS%%@*}
+TARGET_HOST=${TARGET_ADDRESS#*@}
+
+ping -c 1 -q $TARGET_HOST >/dev/null 2>&1 || { echo "Cannot find Stratus connection. Please connect Stratus to your computer via USB"; false; }
 
 ##
 ## All this is done to ensure that we only ask for the SSH password once
@@ -22,8 +25,7 @@ ping -c 1 -q $TARGET_ADDRESS >/dev/null 2>&1 || { echo "Cannot find Stratus conn
 TMP_DIR=$(mktemp -d)
 SSH_CFG=$TMP_DIR/ssh-cfg
 SSH_SOCKET=$TMP_DIR/ssh-socket
-TARGET_USER=root
-TARGET_PATH=/$TARGET_USER/$INSTALLATION_PACKAGE
+##TARGET_PATH=/$TARGET_USER/$INSTALLATION_PACKAGE
 
 ##
 ## Install cleanup routines
@@ -32,7 +34,7 @@ for sig in SIGTERM ERR EXIT; do trap "_term $sig" $sig; done
 _term() {
   trap "" SIGTERM ERR EXIT
   # Close the SSH tunnel:
-  ssh -F "$SSH_CFG" -S "$SSH_SOCKET" -O exit "$TARGET_ADDRESS" >/dev/null 2>&1
+  ssh -F "$SSH_CFG" -S "$SSH_SOCKET" -O exit "$TARGET_HOST" >/dev/null 2>&1
   rm -rf $TMP_DIR
   exit 0
 }
@@ -45,24 +47,25 @@ Host *
 ENDCFG
 
 # Open an SSH tunnel:
-ssh -F "$SSH_CFG" -f -N -l $TARGET_USER $TARGET_ADDRESS
+ssh -F "$SSH_CFG" -f -N -l $TARGET_USER $TARGET_HOST
 
 # Upload the installation file:
-scp -F "$SSH_CFG" "${INSTALLATION_PACKAGE}" "$TARGET_USER@$TARGET_ADDRESS:/$TARGET_PATH"
+scp -F "$SSH_CFG" "${INSTALLATION_PACKAGE}" "$TARGET_ADDRESS:"
 
 # Install the installation file:
-ssh -F "$SSH_CFG" "$TARGET_USER@$TARGET_ADDRESS:/$TARGET_USER" -T <<ENDSSH
+ssh -F "$SSH_CFG" "$TARGET_ADDRESS" -T <<ENDSSH
+[[ -w "/" ]] || SUDO=sudo
 cd /
-tar -xzf $TARGET_PATH
+\$SUDO tar -xzf \$HOME/$INSTALLATION_PACKAGE
 echo "Testing installation"
 faust --help || { echo "Installation failed"; exit 1; }
 
 echo Running basic interface tests
-cd /root
+cd
 faust2stratus tester.dsp -stratusinstall &&
-python3 tester.py "/opt/update/sftp/firmware/effects/2ce39b6c-10fa-11ef-9fc3-eb5bff98409a.so"
+\$SUDO python3 /root/tester.py "/opt/update/sftp/firmware/effects/2ce39b6c-10fa-11ef-9fc3-eb5bff98409a.so"
 RC=\$?
-rm -f "/opt/firmware/effects/2ce39b6c-10fa-11ef-9fc3-eb5bff98409a".*
+\$SUDO rm -f "/opt/firmware/effects/2ce39b6c-10fa-11ef-9fc3-eb5bff98409a".*
 [[ \$RC -eq 0 ]] || { echo "Test execution failed"; exit 1; }
 
 echo Installation succeeded
