Fully working installs and v2 doc

diff --git a/srcs/install/install-sdk b/srcs/install/install-sdk
--- a/srcs/install/install-sdk
+++ b/srcs/install/install-sdk
@@ -57,11 +57,13 @@ tar -xzf $TARGET_PATH
 echo "Testing installation"
 faust --help || { echo "Installation failed"; exit 1; }
 
-#Not working yet
-#echo Running basic interface tests
-#cd /root
-#faust2stratus tester.dsp true || { echo "Test DSP compile failed"; exit 1; }
-#python3 tester.py || { echo "Test execution failed"; exit 1; }
+echo Running basic interface tests
+cd /root
+faust2stratus tester.dsp --stratusc --stratusinstall &&
+python3 tester.py "/opt/firmware/effects/2ce39b6c-10fa-11ef-9fc3-eb5bff98409a.so"
+RC=\$?
+rm -f "/opt/firmware/effects/2ce39b6c-10fa-11ef-9fc3-eb5bff98409a".*
+[[ \$RC -eq 0 ]] || { echo "Test execution failed"; exit 1; }
 
 echo Installation succeeded
 echo You can now use the faustOnStratus command to install your DSP files on the Stratus
