Tweaks

diff --git a/srcs/install/sdk-build-effect b/srcs/install/sdk-build-effect
--- a/srcs/install/sdk-build-effect
+++ b/srcs/install/sdk-build-effect
@@ -8,12 +8,14 @@
 ##
 ##     sdk-build-effect <location-of-your-dsp-file>
 ##
+## All other arguments are passed to the faust2stratus script.
+##
 ## If the build works, your shared library will be on the Stratus, and will also
 ## have been copied back to the same folder as your DSP file, along with the C++
 ## code generated by the Faust compiler.
 ##
 DSP=${1:?First argument must be the Faust DSP file path}
-CINTERFACE=${2:-false}
+shift
 
 DSP=$(realpath $DSP)
 DSP_FILENAME=$(basename $DSP)
@@ -66,9 +68,7 @@ scp -F "$SSH_CFG" "${DSP}" "$TARGET_USER@$TARGET_ADDRESS:/$TARGET_PATH"
 # Build the effect:
 ssh -F "$SSH_CFG" "$TARGET_USER@$TARGET_ADDRESS:/$TARGET_USER" -T <<ENDSSH
 cd /$TARGET_USER
-echo "Building $DSP_FILENAME"
-[[ "$CINTERFACE" == "true" ]] && export CINTERFACE
-faust2stratus "$DSP_FILENAME" || { echo "Build of $DSP_FILENAME failed"; exit 1; }
+faust2stratus "$DSP_FILENAME" "$@" || { echo "Build of $DSP_FILENAME failed"; exit 1; }
 echo Build of $DSP_FILENAME succeeded
 ENDSSH
 
